name: Create Page Minify Branch

on:
  push:
    branches:
      - main

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name  "thaim"
          git config user.email "thaim@users.noreply.github.com"
          git switch -c page-minify
          touch test.txt
          echo "Today's date is $(date)" > test.txt
          git add .
          git commit -m "Create page minify branch"
          git push -f -u origin page-minify
          
          
