name: Create Page Minify Branch

on:
  push:
    branches:
      - main

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name  "PanNyaa"
          git config user.email "PanNyaa@users.noreply.github.com"
          
          git switch -c page-minify
          
          : # touch test.txt
          : # echo "Today's date is $(date)" > test.txt
          
          yarn install
          yarn add html-minifier
          yarn add clean-css-cli
          yarn add uglify-js
          
          : # yarn html-minifier --help
          
          SIZE_s=(ls−l∣grep−E"(html∣css∣js)" | awk '{s+=$5}')
          
          : # html minify
          yarn html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --continue-on-parse-error index.html -o index.html
          
          : # CSS minify
          yarn cleancss -O2 -o style.css style.css
          : # yarn html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --continue-on-parse-error --minify-css true style.css -o style.css
          
          : # yarn html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --continue-on-parse-error --minify-js true script.js -o script.js
          
          : # js minify
          yarn uglifyjs script.js -c -m --mangle-props -o script.js
          
          : # --mangle-propsを付けるとパーティクルのコネクトラインが消える？
          : # yarn uglifyjs p.js -c -m --mangle-props -o p.js
          yarn uglifyjs p.js -c -m -o p.js
          
          : # --mangle-propsを付けるとパーティクルのコネクトラインが消える？
          yarn uglifyjs onload.js -c -m -o onload.js
          
          SIZE_d=$(ls -l | grep -E "(html|css|js)$" | awk '{s+=$5}')
          ANSWER=$((SIZE_s - SIZE_d))
        
          SIZE_s_kb=$((SIZE_s / 1024))
          SIZE_d_kb=$((SIZE_d / 1024))
          ANSWER_kb=$((ANSWER / 1024))
          
          echo "圧縮前後の差分：$ANSWER_kb KB" >> result.md
          
          echo "node_modules" >> .gitignore
          echo "yarn.lock" >> .gitignore
          echo "package.json" >> .gitignore
          : # git rm --cached -r node_modules
          
          git add .
          git commit -m "Create page minify branch"
          git push -f -u origin page-minify
