name: Create Page Minify Branch

on:
  push:
    branches:
      - main

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name  "PanNyaa"
          git config user.email "PanNyaa@users.noreply.github.com"
          git switch -c page-minify
          : # touch test.txt
          : # echo "Today's date is $(date)" > test.txt
          yarn install
          yarn add html-minifier
          yarn html-minifier --help
          yarn html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true *.html *.css *.js
          git add .
          git commit -m "Create page minify branch"
          git push -f -u origin page-minify
