name: Minify

on:
  push:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn
        run: yarn install
      - name: Minify html, css, and js files
        run: yarn minify
      - name: Push minified files to page-minify branch
        run: git push origin page-minify
