name: Create Page Minify Branch

on:
  push:
    branches:
      - main

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name  "PanNyaa"
          git config user.email "PanNyaa@users.noreply.github.com"
          
          git switch -c page-minify
          
          : # touch test.txt
          : # echo "Today's date is $(date)" > test.txt
          
          yarn install
          yarn add html-minifier
          yarn add clean-css-cli
          yarn add uglify-js
          
          : # yarn html-minifier --help
          
          : # minify前のhtml,css,jsのファイルサイズ
          SIZE_html_s=`find . -type f -name "*.html" -exec cat {} + | wc -c`
          SIZE_css_s=`find . -type f -name "*.css" -exec cat {} + | wc -c`
          SIZE_js_s=`find . -type f -name "*.js" -exec cat {} + | wc -c`
          SIZE_before=$(( SIZE_html_s + SIZE_css_s + SIZE_js_s ))
          
          : # html minify
          yarn html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --continue-on-parse-error index.html -o index.html
          
          : # CSS minify
          yarn cleancss -O2 -o style.css style.css
          : # yarn html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --continue-on-parse-error --minify-css true style.css -o style.css
          
          : # yarn html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --continue-on-parse-error --minify-js true script.js -o script.js
          
          : # js minify
          yarn uglifyjs script.js -c -m --mangle-props -o script.js
          
          : # --mangle-propsを付けるとパーティクルのコネクトラインが消える？
          : # yarn uglifyjs p.js -c -m --mangle-props -o p.js
          yarn uglifyjs p.js -c -m -o p.js
          
          : # --mangle-propsを付けるとパーティクルのコネクトラインが消える？
          yarn uglifyjs onload.js -c -m -o onload.js
          
          : # minify後のhtml,css,jsのファイルサイズ
          SIZE_html_d=`find . -type f -name "*.html" -exec cat {} + | wc -c`
          SIZE_css_d=`find . -type f -name "*.css" -exec cat {} + | wc -c`
          SIZE_js_d=`find . -type f -name "*.js" -exec cat {} + | wc -c`
          SIZE_after=$(( SIZE_html_d + SIZE_css_d + SIZE_js_d ))
          
          : # minify前の各種ファイル群合計サイズからminify後の合計サイズを引いた差を計算する
          SIZE_diff=`echo "$SIZE_before - $SIZE_after" | bc -l`
          SIZE_diff_kb=`echo "scale=2; $SIZE_diff / 1024" | bc`

          echo "html : $SIZE_html_s -> $SIZE_html_d (byte)" >> result.txt
          echo "css : $SIZE_css_s -> $SIZE_css_d (byte)" >> result.txt
          echo "js : $SIZE_js_s -> $SIZE_js_d (byte)" >> result.txt
          echo "total size : $SIZE_before -> $SIZE_after (byte)" >> result.txt
          echo "total minify : $SIZE_diff_kb (Kbyte)" >> result.txt
          
          TZ='Asia/Tokyo'
          YYYYMMDD=`date +"%Y-%m-%d-%H:%M"`
          
          echo "node_modules" >> .gitignore
          echo "yarn.lock" >> .gitignore
          echo "package.json" >> .gitignore
          : # git rm --cached -r node_modules
          
          git add .
          git commit -m "$YYYYMMDD : total minify $SIZE_diff_kb (Kbyte)"
          git push -f -u origin page-minify
